sandbox_engineering:
  adapter: redshift
  database: <%= ENV['REDSHIFT_SANDBOX_DB'] || ENV['REDSHIFT_SANDBOX_PREFIX'].try(:+, '_engineering') || 'engineering' %>
  host: mxl.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: mxl
  password: sc0utAd$
  pool: 2

production_engineering:
  adapter: redshift
  database: production
  host: thinknear-production-2015-03.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: scout
  password: sc0utAd$
  pool: 2

sandbox_ops:
  adapter: redshift
  database: <%= ENV['REDSHIFT_SANDBOX_DB'] || ENV['REDSHIFT_SANDBOX_PREFIX'].try(:+, '_ops') || 'ops' %>
  host: mxl.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: mxl
  password: sc0utAd$
  pool: 2

production_ops:
  adapter: redshift
  database: production
  host: thinknear-ops-2014-09.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: scout
  password: sc0utAd$
  pool: 2

sandbox_avails:
  adapter: redshift
  database: <%= ENV['REDSHIFT_SANDBOX_DB'] || ENV['REDSHIFT_SANDBOX_PREFIX'].try(:+, '_avails') || 'avails' %>
  host: mxl.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: mxl
  password: sc0utAd$
  pool: 2

production_avails:
  adapter: redshift
  database: production
  host: thinknear-avails-2015-03.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: scout
  password: sc0utAd$
  pool: 2

development:
  adapter: redshift
  database: dev
  host: mxl.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: mxl
  password: sc0utAd$
  pool: 2
