development:
  adapter: redshift
  database: dev
  host: mxl.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: mxl
  password: sc0utAd$
  pool: 2

production:
  adapter: redshift
  database: production
  host: thinknear-production.chfzr25wnyxl.us-east-1.redshift.amazonaws.com
  port: 5439
  username: scout
  password: sc0utAd$
  pool: 2
